//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopWinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class croatian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal croatian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopWinForms.Properties.croatian", typeof(croatian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prebaci Igrača.
        /// </summary>
        internal static string cntxMenuStripFavPlayer {
            get {
                return ResourceManager.GetString("cntxMenuStripFavPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posjetitelji.
        /// </summary>
        internal static string dataGridAttendance {
            get {
                return ResourceManager.GetString("dataGridAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gost.
        /// </summary>
        internal static string dataGridAwayTeam {
            get {
                return ResourceManager.GetString("dataGridAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan.
        /// </summary>
        internal static string dataGridCaptain {
            get {
                return ResourceManager.GetString("dataGridCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaćin.
        /// </summary>
        internal static string dataGridHomeTeam {
            get {
                return ResourceManager.GetString("dataGridHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika.
        /// </summary>
        internal static string dataGridImage {
            get {
                return ResourceManager.GetString("dataGridImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        internal static string dataGridLoacation {
            get {
                return ResourceManager.GetString("dataGridLoacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string dataGridName {
            get {
                return ResourceManager.GetString("dataGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj.
        /// </summary>
        internal static string dataGridNumber {
            get {
                return ResourceManager.GetString("dataGridNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija.
        /// </summary>
        internal static string dataGridPosition {
            get {
                return ResourceManager.GetString("dataGridPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljeni Igrači, obaberi tri (3):.
        /// </summary>
        internal static string lblFavPlayers {
            get {
                return ResourceManager.GetString("lblFavPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rang lista prema broju posjetitelja.
        /// </summary>
        internal static string lblFavTeamMatches {
            get {
                return ResourceManager.GetString("lblFavTeamMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rang lista.
        /// </summary>
        internal static string lblRangList {
            get {
                return ResourceManager.GetString("lblRangList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rang Liste Svjetskog Nogometnog Prvenstva.
        /// </summary>
        internal static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljena reprezentacija &lt;odaberi&gt;.
        /// </summary>
        internal static string menuStripFavTeamComboBox {
            get {
                return ResourceManager.GetString("menuStripFavTeamComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoteka.
        /// </summary>
        internal static string menuStripFile {
            get {
                return ResourceManager.GetString("menuStripFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispis Rang Lista.
        /// </summary>
        internal static string menuStripFilePrintStats {
            get {
                return ResourceManager.GetString("menuStripFilePrintStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        internal static string menuStripSettings {
            get {
                return ResourceManager.GetString("menuStripSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudjelovao.
        /// </summary>
        internal static string rbSortGamesPlayed {
            get {
                return ResourceManager.GetString("rbSortGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi.
        /// </summary>
        internal static string rbSortGoals {
            get {
                return ResourceManager.GetString("rbSortGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žuti kartoni.
        /// </summary>
        internal static string rbSortYellowCards {
            get {
                return ResourceManager.GetString("rbSortYellowCards", resourceCulture);
            }
        }
    }
}
